CREATE TABLE `Notenspiegel` (
  `id` varchar(100) NOT NULL,
  `studentId` varchar(100) DEFAULT NULL,
  `bewertung` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `vermerk` varchar(50) DEFAULT NULL,
  `versuch` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `semester` varchar(50) DEFAULT NULL,
  `pruefungsdatum` date DEFAULT NULL,
  `pruefungstext` varchar(200) DEFAULT NULL,
  `pruefungsnr` int DEFAULT NULL,
  `parentId` varchar(100) DEFAULT NULL,
  `prueferId` varchar(100) DEFAULT NULL,
  `cp` int DEFAULT '0',
  `cp_to_achieve` int DEFAULT NULL,
  `pruefungsId` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `studentId` (`studentId`),
  KEY `fk_pruefer` (`prueferId`),
  KEY `fk_parent` (`parentId`),
  CONSTRAINT `fk_parent` FOREIGN KEY (`parentId`) REFERENCES `Notenspiegel` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pruefer` FOREIGN KEY (`prueferId`) REFERENCES `Professor` (`id`),
  CONSTRAINT `notenspiegel_ibfk_1` FOREIGN KEY (`studentId`) REFERENCES `Studenten` (`id`) ON DELETE CASCADE
)