 CREATE TABLE `Pruefungen` (
  `id` varchar(100) NOT NULL,
  `parentId` varchar(100) DEFAULT NULL,
  `datum` date DEFAULT NULL,
  `beginn` time DEFAULT NULL,
  `ende` time DEFAULT NULL,
  `pruefer` varchar(100) DEFAULT NULL,
  `pruefungensnr` int NOT NULL,
  `studiengangId` varchar(100) DEFAULT NULL,
  `raum` varchar(20) DEFAULT NULL,
  `ruecktrittbis` date DEFAULT NULL,
  `credit_point` int DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `semester` varchar(20) DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `parentId` (`parentId`),
  KEY `pruefer` (`pruefer`),
  KEY `studiengangId` (`studiengangId`),
  CONSTRAINT `pruefungen_ibfk_1` FOREIGN KEY (`parentId`) REFERENCES `Pruefungen` (`id`) ON DELETE CASCADE,
  CONSTRAINT `pruefungen_ibfk_3` FOREIGN KEY (`pruefer`) REFERENCES `Professor` (`id`) ON DELETE SET NULL,
  CONSTRAINT `pruefungen_ibfk_4` FOREIGN KEY (`studiengangId`) REFERENCES `Studiengang` (`id`) ON DELETE CASCADE
)